#pragma once

#include <ntdef.h>
#include <ntifs.h>

#define IO_SEND_PROCESSID CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0701, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SEND_PING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0702, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SEND_CLICK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0703, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

NTSTATUS Create(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS Close(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS IoControl(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS Pnp(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS Power(PDEVICE_OBJECT DeviceObject, PIRP Irp);
NTSTATUS InterIoCtl(PDEVICE_OBJECT DeviceObject, PIRP Irp);

